import { defineConfig } from 'orval';

export default defineConfig({
  petstore: {
    input: {
      target: './openapi.yaml',
    },
    output: {
      target: './src/api/endpoints',
      schemas: './src/api/models',
      httpClient: 'axios',
      client: 'react-query',
      mode: 'tags',
      clean: true,
      prettier: true,
      override: {
        header: (info) => [`Generated by Orval`, `Do not edit manually.`, ...(info.title ? [info.title] : [])],
        mutator: {
          path: './api/mutator/custom-instance.ts',
          name: 'customInstance',
        },
      },
    },
  },
});
